services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - LOTTERY_SERVICE_URL=http://lottery-service:3002
      - JWT_SECRET=your-secret-key-change-this
    depends_on:
      - auth-service
      - lottery-service
    networks:
      - loto-network
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    environment:
      - PORT=3001
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-secret-key-change-this
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - loto-network
    restart: unless-stopped

  lottery-service:
    build: ./lottery-service
    environment:
      - PORT=3002
      - DB_HOST=lottery-db
      - DB_PORT=5432
      - DB_NAME=lottery_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-secret-key-change-this
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - lottery-db
      - rabbitmq
    networks:
      - loto-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - loto-network
    restart: unless-stopped

  auth-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - loto-network
    restart: unless-stopped

  lottery-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=lottery_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - lottery-db-data:/var/lib/postgresql/data
    networks:
      - loto-network
    restart: unless-stopped

networks:
  loto-network:
    driver: bridge

volumes:
  auth-db-data:
  lottery-db-data: